### ISSUE TITLE
Passing custom VLC arguments?

### ISSUE THREAD

**Issue by dhirwin** [RSATom/WebChimera#116]
With the old VLC plugin we were able to pass in custom VLC arguments (network-caching=300, rtsp-tcp, ipv4-timeout=15000) to VLC (i.e. LibVLC) but I don't see any available methods in the Wiki that allows me to do this via the WebChimera plugin. The "addPlayer" function takes parameters but other than "buffering" none that appear to be what I'm looking for. Hopefully I'm just looking in the wrong spot.

**Comment by jaruba** [comment]
http://wiki.webchimera.org/VlcArgs

**Comment by jaruba** [comment]
Also, if you don't need the User Interface that WebChimera Player provides, you can just use WebChimera Plugin directly and it's API.

[Embedding WebChimera Plugin](http://wiki.webchimera.org/Plugin_Embedding)
[WebChimera Plugin JS API](http://wiki.webchimera.org/Plugin_JavaScript_API)

But the player wraps all the plugin api functions in different functions as it requires additional actions in order to work correctly.

**Comment by RSATom** [comment]
I think this question was answered pretty well...

**Comment by dhirwin** [comment]
Yes, thank you for your response...very helpful.
