### ISSUE TITLE
webchimera on linux ?

### ISSUE THREAD

**Issue by smolleyes** [RSATom/WebChimera#75]
hi

how can we use webchimera on linux? is it possible now ?

thanks a lot for this great plugin !

**Comment by RSATom** [comment]
Linux version is not finished yet. Sorry.

**Comment by smolleyes** [comment]
Hello

You re already doing a GREAT job so np i ll wait :) 

But do you think it will be long ? (Just to have an idear :p)

**Comment by RSATom** [comment]
Since you are the first donator of this project (btw what do you think about to be in our "THANKS" list?), it seems I have to start work on linux version right after the next release, which will be (I hope) within a weak. I hope it will take about two weeks, maybe less.

**Comment by smolleyes** [comment]
thanks a lot rsatom and i ll be happy to donate again to congratulate you :)

++

**Comment by RSATom** [comment]
> As i said before, this plugin with nwjs is a real dream for me and many nwjs dev i think !

How about advertise it in nwjs community then? :) The more users WebChimera will have, the faster it will evolve.

**Comment by smolleyes** [comment]
i will no problems :)

**Comment by smolleyes** [comment]
done :)

do you think x265/hevc will be supported soon ?

**Comment by RSATom** [comment]
is it supported by Vlc player?

**Comment by smolleyes** [comment]
in lastest release yes, i tried yesterday and it carsh, not sure it s in the mime types of the plugins but supported normally

**Comment by smolleyes** [comment]
maybe adding video/x-h265 can fix this

**Comment by smolleyes** [comment]
hevc & vp9 decoding support have been introduced in the 2.1.1 release

**Comment by RSATom** [comment]
do you have some x265/hevc example to try?

**Comment by RSATom** [comment]
WebChimera embeds almost all plugins from Vlc player, so if some format is supported by Vlc player - it should be supported by WebChimera.

**Comment by smolleyes** [comment]
http://www.h265files.com/

**Comment by RSATom** [comment]
thanks, I'll try them.

**Comment by RSATom** [comment]
All files from this page works fine. At least on windows (with libvlc 2.1.5).

**Comment by smolleyes** [comment]
OK strange

Will report if i found a file not working :)

**Comment by smolleyes** [comment]
hello RSATom, any progress on this :) ?

**Comment by RSATom** [comment]
Yes, I found the reason why plugin did not work at some conditions. Trying to find way to workaround it without possible side effects.

**Comment by RSATom** [comment]
@smolleyes, btw, what linux distro do you use?

**Comment by smolleyes** [comment]
hello

i m on ubuntu 14.04.2 now :)

**Comment by RSATom** [comment]
Ok, how do you distribute (or plan distribute) your Node-Webkit application? PPA?

**Comment by smolleyes** [comment]
i distribute it thru zip files but have some deb files too yes, not a problem... why?

**Comment by yipperr** [comment]
hello sorry to intrude but do you have any plans to port your plugin to google chrome with the ppapi plugin i have read in the videolan forum that libvlc is already ported to nacl and i think there is support for qt as well

**Comment by RSATom** [comment]
@yipperr, I didn't investigate this question yet, and don't have such plans for near future since I'm very limited in free time, sorry.
But if (and when) Videolan team will release ppapi pluging - I think port WebChimera become pretty easy task.

Btw, where did you read about libvlc port to nacl?

**Comment by RSATom** [comment]
[found it](https://forum.videolan.org/viewtopic.php?f=5&t=107178), but:
> j-b: libVLC was ported to NaCL, but not any plugins.

libvlc without plugin is useless...

**Comment by yipperr** [comment]
is there any benefit for running libvlc over nacl  ?

**Comment by RSATom** [comment]
> i distribute it thru zip files but have some deb files too yes, not a problem... why?

this means it will be enough for you if just will get npWebChimera.so? (i.e. without PPA)

**Comment by RSATom** [comment]
@yipperr don't see any benefit except it will work on Chrome....

**Comment by yipperr** [comment]
hello wasn't the magic player used by acestream a qml player frontend over the npapi webplugin 
http://magicplayer.torrentstream.net/

**Comment by smolleyes** [comment]
yes .so is enough , np ;)

**Comment by RSATom** [comment]
@yipperr, I think yes it is.

**Comment by jaruba** [comment]
That is highly possible, I was inspired by that player in the beginning because it made sense to try to make a block based UI, considering that QML is a block based environment. The thought came to mind that it could of also been made in QML.

**Comment by smolleyes** [comment]
hello RSATom :)

some progress on the linux .so :D ? (you ll hate me lol)

**Comment by yipperr** [comment]
@jaruba  me too the magic player looked stunning i want to create a similar player using the pppapi for chrome but this would mean i need qt and vlc ported to nacl

**Comment by RSATom** [comment]
@smolleyes, it woks, but if you want try it right now you have to build it yourself. And now it's compatible only with Qt 5.4. If you want - I can give you (tomorrow) some instructions how to build it...

**Comment by smolleyes** [comment]
nice :)

ok let me know ! 

thanks

**Comment by jaruba** [comment]
@yipperr Hola is trying the same thing with [Hola Player](http://hola.org/publishers)

**Comment by yipperr** [comment]
@jaruba 

i tried the video player they have no support for linux platforms yet so nothing worked for me. it's not  the same thing hola  claims to be anonymizers by using a model where you can connect one of the many nodes in many countries and and get over your restriction and  your somehow made a node on the network (mind you this is not stated explicitly anywhere on there site) so that other can you use you to relay traffic as well this is the p2p network there talking about

now they claim to use this network of p2p as a cdn with the intent of distributing video faster through this p2p network do you have any idea how there achiveing this ?  he claims he can play mkv container as well last time i checked the video tag had issues parsing that container format

**Comment by jaruba** [comment]
@yipperr Hola Player is new, I sent an email to them when they first released this player to try to gather some information about it, they wore not very explicit but I think I mostly understand how it works.

Hola Plugin is a PPAPI plugin that works as a proxy client (with some added features for the player in the newest release), if you want their Player to work, you need to update it. Updating it will also add Hola to your Icon Tray (so this means your actually installing 2 things now, the PPAPI proxy client and what I believe is a new piece of software that might be made in node-webkit).

I think the part of the plugin that is not the PPAPI is using node-webkit to activate peerflix on your local machine with the magnet link you want to view then somehow passing this information to the PPAPI so it can add their player in the page your viewing.

I think their passing the magnet link to the local software by posting it to their servers with the PPAPI then fetching it from the servers to the local software.

Peerflix then creates a readable stream from your local machine, so it doesn't need to be connected to the browser, it just needs to get the target magnet link, and as it's passing back a link too (through their servers again), that link will also transcend any browser connectivity requirements.

Their not playing any mkv files, only mp4 files that the video tag supports, for any other file types their just opening vlc locally to play them. That's why I'm expecting them to end up by using ffmpeg transcoding, because their putting a lot of work in their html5 player, their not doing this yet though. (I agree this requires a lot of resources and is a bad idea, but it may be the only choice for them in the future)

**Did you managed to release the peerflix npapi plugin that you where working on ?**

I learned enough C++ to make it work. It's practically an interface for the peerflix command line, it parses the peerflix command line output and passes it to the browser, then I use WebChimera to play the result, this works but the info it parses from peerflix is kind of laggy (because peerflix itself checks the data from torrent-stream periodically, then the plugin checks peerflix's data periodically, so this creates some lag), but the streaming itself works great.

The plugin is finished for about a week and a half now, I just didn't get around to packaging it and posting the code (as I just learned C++ I'm a bit unsure of how to post a FireBreath plugin as open source on GitHub, maybe @RSATom can help me a bit with this)

Instead of wasting more time on doing this I tried working with node-webkit directly to see what I can do with it, and I'm almost done with an exciting new app made in it with peerflix + webchimera that I will be unveiling soon.

**Comment by RSATom** [comment]
@jaruba could you please clarify a little, what goal you want to achieve by peerflix npapi plugin?

**Comment by jaruba** [comment]
@rsatom I have no goal with this, I just think it will be a fun project to post as open source, peerflix has a lot of fans and a peerflix npapi will give a lot of Web Developers the chance to play with WebChimera and Peerflix directly in their browser with ease by just using the JS API's of these plugins.

**Comment by RSATom** [comment]
I just try understand what it can.
And I thought peerflix is JS lib? Am I was wrong? How did you attach it to c++?

**Comment by jaruba** [comment]
Peerflix can also be run from cmd.exe with node.js (node.exe can also be used as a standalone file).

So I can call it through the command line and it outputs the data that it gets from torrent-stream. (as shown on the [project page](https://github.com/mafintosh/peerflix#usage))

I just need to know how to package the plugin with node.exe and peerflix embedded into it so I can access the peerflix command line with the plugin on any machine it's installed on.

**Comment by RSATom** [comment]
Ah... understand, but I think it's very reliable way - but as start point - it's good enough I think.

What files node.js package consists? Does it only one .exe?

**Comment by jaruba** [comment]
I think so, I found [this comment](https://github.com/joyent/node/issues/3978#issuecomment-8391612) and it says:

"Look, if you need just a portable Node.js engine, you could simply grab http://nodejs.org/dist/latest/node.exe and save it somewhere and run it whenever you want a JavaScript file executed: \path\to\saved\node.exe scriptname.js. It's that simple, and I cannot imagine a portable version simpler than a single executable file. (See the “Installing without building” section in the “Installation” article of the Node's wiki for more details, if you need them.)"

**Comment by RSATom** [comment]
Where it search modules used in scriptname.js? Can it use it from online sources, or one have to have them near node.exe?

**Comment by jaruba** [comment]
needs absolute or relative path to local js file (I don't think it supports remote file location)

**Comment by RSATom** [comment]
Can one .js file use another .js file (something like "include")?

**Comment by jaruba** [comment]
Yes, it uses ```require``` and all the modules (js files) that are required by a js file, need to be in the ```node_modules``` folder relative to the js file that called ```require```

**Comment by RSATom** [comment]
sounds pretty easy

**Comment by jaruba** [comment]
I'm gonna remake the plugin under a different name, and then if you want to help and can stay on gitter chat or mail for a bit, I might be able to release this today with your help.

The things I still need to do:

- include files in the plugin package (node.exe and peerflix module)

- get absolute path of the plugin install directory (to use when calling cmd.exe to run node.exe)

- build the project into a msi installer (for this one I think there is a video tutorial from FireBreath, just need to watch it)

- know what files to put on github from the package (or do I just put the entire FireBreath folder on GitHub?)

**Comment by RSATom** [comment]
Sorry, don't have time for this right now, but:

> include files in the plugin package (node.exe and peerflix module)

is tricky (very not obvious) part, I always stuck on this, when need add new files to installer.

> get absolute path of the plugin install directory in C++ (to use when calling cmd.exe to run node.exe)

http://www.firebreath.org/display/documentation/Tips+and+Tricks#TipsandTricks-Gettingthepathandfilenameoftheplugin%28DLL,.so,or.dylib%29

> build the project into a msi installer (for this one I think there is a video tutorial from FireBreath, just need to watch it)

template for msi already there (look Win/WIX folder ), just may need some adjustments

> know what files to put on github from the package (or do I just put the entire FireBreath folder on GitHub?)

Put only your plugin files. Later we could add  firebreath repo as submodule (https://github.com/RSATom/WebChimera/tree/master/deps). And maybe I will do it for you (it will be faster ;)

**Comment by yipperr** [comment]
**Updating it will also add Hola to your Icon Tray (so this means your actually installing 2 things now, the PPAPI proxy client and what I believe is a new piece of software that might be made in node-webkit).**
i noticed this too i was left taking guesses at what the other plugin was doing your idea on  they running a node-webkit binary to run peerflix seems possible but very inefficient because they  only need the node run time and have no use for the rest of the node-webkit stuff like the  layout engine and parser so i think there using more of custom solution it can't be that general also there can be the possibilty the there just using torrent-stream over there own frontend... we can only make guesses...

**I think their passing the magnet link to the local software by posting it to their servers with the PPAPI then fetching it from the servers to the local software**

do you have any idea why there doing this ? 

this from the publisher section of hola
**Hola's P2P network makes the typically expensive task of delivering video now absolutely free, since the network of viewers is now the network of CDN servers.**

i think you need to be a premium member to publish content but this also mean that those members content are cached by hola using there plugins on the many host computers they have access to ..this sounds like a breach of privacy because none of this was mentioned in the plugins download page in chrome

**Comment by yipperr** [comment]
@RSATom 

how hard do you think it is to make a ppapi plugin for vlc having already libvlc access in nacl runtime with 
in the gsoc 2014 it said it was a priority to get this done and i thinks it usefull but never worked with libvlc but i have read the nacl/pnacl runtime and the ppapi

**Comment by jaruba** [comment]
**this sounds like a breach of privacy because none of this was mentioned in the plugins download page in chrome this would also mean the surge of new people who download there plugins (both have to be installed will be used as a cache for there cdn)**

Sounds like the tor network, I think most of what they write on the site is lies/half truths to glorify their product for marketing purposes. As I said I sent an email to them to understand how it works and it's limitations better and they wore very evasive on responses. I'm sure their doing something bad, just not sure what. :)

**Comment by RSATom** [comment]
@yipperr, i think it's not solvable task by any single man. It's the same level task as porting Vlc to WinRT for example (i.e. absolutely new platform with absolutely new API) - guys from Videolan did it about two years if I not mistaken...

**Comment by jaruba** [comment]
@rsatom Are all the FireBreath Plugins installed in the %AppData% folder like webchimera is? If so I could just run node.exe relative to %AppData% considering I'm using cmd.exe for this. That way I wouldn't even need the absolute path for this.

**Comment by RSATom** [comment]
If you will use default .wix template - yes.

**Comment by smolleyes** [comment]
hello rsatom

What s up with this .so or build instructions :) ?

Thanks

**Comment by RSATom** [comment]
Sorry, it was hard week...
Ok, let's start:
1) install Qt 5 from http://www.qt.io/download-open-source/
2) `sudo apt-get install build-essential cmake git`
3) `export CMAKE_PREFIX_PATH=~/Qt/5.4/gcc_64`
4) `git checkout  https://github.com/RSATom/WebChimera.git && cd WebChimera`
5) `make prep && make`

**Comment by l4u** [comment]
I got these errors https://gist.github.com/l4u/2afb1e681a19c23f026b

**Comment by RSATom** [comment]
It missed c++11 support. Are you still use clang?

**Comment by RSATom** [comment]
maybe you just need `make prep` after `git pull`?

**Comment by l4u** [comment]
I run `cmake .` and it works now.

**Comment by RSATom** [comment]
Great! It's because `-std=c++11` was added recently to projectDef.cmake

**Comment by RSATom** [comment]
Now it's possible to build `WebChimera` with Qt version which come with latest Ubuntu (Qt 5.2.1):
1) `sudo apt-get install build-essential cmake git libvlc-dev qt5-default qtdeclarative5-dev qtdeclarative5-qtquick2-plugin qtdeclarative5-quicklayouts-plugin`
2) `git checkout  https://github.com/RSATom/WebChimera.git && cd WebChimera`
3) `make prep && make`

**Comment by RSATom** [comment]
btw, @jaruba, could you please try test `WebChimera Player` on Ubuntu (if you can)? By some reason plugin is not loading in your demos(both on `webchimera.org` and `jaruba.github.io`), but works fine in my demos (maybe because they much simpler, and don't use something?)

**Comment by RSATom** [comment]
basic wiki added: https://github.com/RSATom/WebChimera/wiki/Ubuntu-build

**Comment by jaruba** [comment]
I would love to, but it isn't that simple as I have to go away for a few days and will only have my laptop with me, which is a bit slow, I could try installing a VM, but might take a few days.

Off the top of my head, I have to ask if you checked the browser console log, because it might just be a javascript incompatibility in webchimera.js

Otherwise, did you add QtGraphicalEffects to the build on Linux too? As that is also a dependency for for the player.

**Comment by RSATom** [comment]
Ok, never mind, I'll try to find problem by myself. It's possible I just missed something.

> Otherwise, did you add `QtGraphicalEffects` to the build on Linux too? As that is also a dependency for the player.
for example this, on linux I'm not statically link Qt5 into the plugin, but use installed Qt. And if some Qml module is not installed it could give some problem. I'll check `QtGraphicalEffects` it's good hint, thanks.

**Comment by RSATom** [comment]
@jaruba in console I only get `TypeError: navigator.plugins['WebChimera Plugin'] is undefined`

**Comment by jaruba** [comment]
than that's one of the problems for sure, as a error in webchimera.js will stop the script.

**Comment by jaruba** [comment]
what browser are you using in ubuntu?

**Comment by RSATom** [comment]
maybe problem is on linux it has name "WebChimera x86_64" - should I rename it?

**Comment by jaruba** [comment]
it should be the same on all platforms.. but I don't think that's what's breaking it

**Comment by jaruba** [comment]
does it also mentione a specific line where that error occures in webchimera.js?

this is my check if the plugin exists:
https://github.com/jaruba/WebChimeraPlayer/commit/075e6ddc6087980e247228c92a0c4800a1e30671

so it does not call ```navigator.plugins['WebChimera Plugin']``` directly to throw such an error.. it only loops between all ```navigator.plugins```

**Comment by RSATom** [comment]
if I run `navigator.plugins['WebChimera Plugin']` in console it returns `undefined`
but if I run `navigator.plugins['WebChimera x86_64']` it returns `Plugin { 0: MimeType, application/x-chimera-plugin: MimeType, description: "", filename: "npWebChimera.so", version: "0.2.4", name: "WebChimera x86_64", length: 1 }`

**Comment by RSATom** [comment]
error is on https://github.com/jaruba/WebChimeraPlayer/blob/master/player/webchimera.js#L241

**Comment by jaruba** [comment]
As a fast test, you could try to change this line:

	if (this.name == "WebChimera Plugin") isInstalled = true;

to:

	if (this.name == "WebChimera x86_64") isInstalled = true;

in ```player\webchimera.js```

**Comment by RSATom** [comment]
It seems I just need to change plugin name.

**Comment by jaruba** [comment]
oh, it makes sense, that is my error completely

**Comment by RSATom** [comment]
so do I need change plugin name or not? :)

**Comment by jaruba** [comment]
You should, as the player should work the same on all platforms, so it needs to check for the same plugin name everywhere

**Comment by RSATom** [comment]
Ok, I'll try, but by some reason `firebreath` uses different names for x86 and x64  plugins. Maybe it has some meaning - I don't sure yet.

**Comment by jaruba** [comment]
If you want, I can look for a way to check the operating system in webchimera.js

and look for the different name only on linux, it should be easier then the problem you described.

**Comment by RSATom** [comment]
it's not about OS, it's about browser build. i.e. x64 OS could run both x64 and x86 applications. And there could be need in x86 and x64 plugins installed simultaneously. But I still don't sure if it's our case. Don't do nothing right now, I'll try to find more info.

**Comment by jaruba** [comment]
I looked for a way to detect the OS from javascript, it seems the only way is to check [navigator.platform](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform) but being as it's going to be deprecated, it shouldn't be used. Instead, as a simpler fix, I could check for both "WebChimera Player" and "WebChimera x86_64"

**Comment by jaruba** [comment]
Could you check and see if the demos on http://jaruba.github.io/WebChimeraPlayer/ work now?

**Comment by RSATom** [comment]
yes, it works now.

**Comment by jaruba** [comment]
I remember now why I removed the implementation to check for the plugin in the commit I mentioned above, it was because it used ```$.each``` which is from jQuery library, and I wanted it to be pure JavaScript (but JS has no equivalent to ```each```), my implementation of a pure javascript solution was very wrong..

**Comment by jaruba** [comment]
You should still try the player a bit, see if everything works correctly, as a qml dependency error will only appear when that part of the code is executed.

**Comment by RSATom** [comment]
yes, of course. Do you check plugin name in version I tried?

**Comment by smolleyes** [comment]
Hi 

Thanks for your work will try it soon

No way To get static libs builds in the future rsatom ?

Thx

**Comment by RSATom** [comment]
it's possible, just didn't think it's needed on linux.

**Comment by RSATom** [comment]
will PPA be not enough?

**Comment by jaruba** [comment]
I changed the script on the main site too, so the demos on the site should work now, also drafted a new release with the fix. Currently I'm checking for "WebChimera Plugin" and "WebChimera x86_64". If  you think I should add checks for more probable names, please tell me.

**Comment by RSATom** [comment]
thanks @jaruba

**Comment by smolleyes** [comment]
PPA  is fine yes for peoples who share their apps thru it but if the dev want To embed the plugin without asking the final user To install qt dep etc... Having the same ZIP than windows might ne a good thing :)

**Comment by RSATom** [comment]
Why not create your own PPA and add dependency on WebChimera PPA? Then all will be installed by one command with all dependencies.

**Comment by smolleyes** [comment]
i will but it s always nice to have the choice and i think many node-webkit will use your plugin and having it all "portable" is a right thing for your project i think :p

**Comment by smolleyes** [comment]
if i foloow your wiki infos

```
smo@smo-ubu:/tmp$ git checkout --recursive https://github.com/RSATom/WebChimera.git && cd WebChimera

fatal: Not a git repository (or any of the parent directories): .git

```

working with git clone

**Comment by smolleyes** [comment]
trying to build now

first error, you need to add libgtk2.0-dev to dependencies

**Comment by smolleyes** [comment]
build complete

got it working in firefox but multiscreen demo carash on the website

no plugin in chrome 

thx :)

**Comment by jaruba** [comment]
make sure your using the latest **stable version** of chrome.

**Comment by smolleyes** [comment]
np it works in node-webkit just no fullscreen

**Comment by smolleyes** [comment]
can use it on linux 32 bits if builded on 32 bits?

**Comment by smolleyes** [comment]
i have Version 41.0.2272.76 (64-bit)

stable version but not sure

**Comment by jaruba** [comment]
I just updated to 41.0.2272.76 m (on win though) and it works, do you have "WebChimera Plugin" in ```chrome://plugins/```, did you enable the plugins on the page (from the small puzzle icon in the corner next to the star)? Is there any error in the console log?

You could try installing the 32 bit version..

**Comment by smolleyes** [comment]
yup jaruba

no i don t have the plugin in chrome://plugins

did you tried it on linux with the lastest nw 12.0 ? i got it loading with nw 0.9.2 but not 0.12

**Comment by jaruba** [comment]
don't have linux installed, wore all versions of nw you tried on 32bit? I would always recommend to everyone using node-webkit to also add

```"chromium-args": "--load-plugin=plugins\\npWebChimera.dll",```

to ```package.json```, as this did wonders in my case!

**Comment by smolleyes** [comment]
ok i ll try

no i use 64 but i distribute 32 and 64 so ... thanks

**Comment by jaruba** [comment]
but the plugin doesn't work in any 64bit nw version.

**Comment by smolleyes** [comment]
i builded it myself, it works with nw 0.9.2 and firefox with 64 bits

no success with nw 12.0 

"webkit": {
    "plugin": true
  },
  "chromium-args": "--load-plugin=plugins/npWebChimera.so"

nothing work

**Comment by jaruba** [comment]
did you try nw 12.0 in 32bit and it didn't work?

**Comment by smolleyes** [comment]
don t have 32 bits linux os for the moment

**Comment by smolleyes** [comment]
but since it works on 0.9.2 it s a nw problem, i posted an issue

**Comment by RSATom** [comment]
@smolleyes 

> working with git clone --recursive :)

sorry, it was typo - fixed.

**Comment by RSATom** [comment]
@jaruba 

> but the plugin doesn't work in any 64bit version of node-webkit. It's only released in 32bit.

Plugin build by default as 32 but module only at Windows. On Mac OS X it is x64, on linux - depends on distribution.

**Comment by RSATom** [comment]
> i will but it s always nice to have the choice and i think many node-webkit will use your plugin and having it all "portable" is a right thing for your project i think :p

Unfortunately there are no such thing as "portable app" in linux world. Any binary application is very tied to specific distribution. So you have to use PPA's (which build binaries for every supported distribution) or build it by hand on specific host.

**Comment by l4u** [comment]
@smolleyes for newer nw, it might be related to chromium's removal of NPAPI on linux too

**Comment by RSATom** [comment]
@l4u, so we have to search another way to embed WebChimera to NW.js... Are you sure NPAPI was removed in chromium?

**Comment by jaruba** [comment]
@RSATom @l4u It wasn't removed, it's the same versions of chrome / chromium on all OS's, they can't remove NPAPI's just from Linux, when it will be removed, it will be removed everywhere. (and that in September)

**Comment by l4u** [comment]
Probably need the flag `enable-npapi`. But it didn't work for me.
